export {default as galleryImage1} from './1.webp'
export {default as galleryImage2} from './2.webp'
export {default as galleryImage3} from './3.webp'
export {default as galleryImage4} from './4.webp'
export {default as galleryImage5} from './5.webp'
export {default as galleryImage6} from './6.webp'
export {default as galleryImage7} from './7.webp'
export {default as galleryImage8} from './8.webp'
